env:
  browser: true
  jest: true
  es2021: true
  # yaml: true
extends: 
  - 'airbnb-base'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
